#!/usr/bin/env python3
"""Generate _site/index.html linking to every rendered notebook HTML.

Usage: build_index.py <site_dir>
Walks <site_dir> for *.html (excluding index.html), groups them by their
parent directory, and writes a simple browsable index at <site_dir>/index.html.
"""

from __future__ import annotations

import html
import sys
from collections import defaultdict
from pathlib import Path


def main() -> int:
    if len(sys.argv) != 2:
        print("usage: build_index.py <site_dir>", file=sys.stderr)
        return 2
    root = Path(sys.argv[1])
    if not root.is_dir():
        print(f"error: {root} is not a directory", file=sys.stderr)
        return 2

    pages = sorted(
        p for p in root.rglob("*.html") if p.name != "index.html"
    )
    groups: dict[str, list[Path]] = defaultdict(list)
    for p in pages:
        rel = p.relative_to(root)
        groups[str(rel.parent)].append(rel)

    out = [
        "<!DOCTYPE html>",
        '<html lang="en"><head><meta charset="utf-8">',
        '<meta name="viewport" content="width=device-width, initial-scale=1">',
        "<title>llm-playground — rendered notebooks</title>",
        "<style>",
        "body{font-family:system-ui,-apple-system,sans-serif;max-width:900px;"
        "margin:2rem auto;padding:0 1rem;line-height:1.6;color:#1a1a1a}",
        "h1{font-size:1.6rem} h2{margin-top:1.8rem;font-size:1.1rem;"
        "border-bottom:1px solid #e2e2e2;padding-bottom:.3rem;color:#444}",
        "ul{list-style:none;padding-left:0} li{margin:.25rem 0}",
        "a{color:#0a58ca;text-decoration:none} a:hover{text-decoration:underline}",
        ".meta{color:#666;font-size:.9rem}",
        "</style></head><body>",
        "<h1>llm-playground — rendered notebooks</h1>",
        f'<p class="meta">{len(pages)} notebooks across {len(groups)} '
        f"directories. Auto-generated by the <code>render-notebooks</code> "
        f"GitHub Actions workflow.</p>",
    ]
    for grp in sorted(groups):
        label = grp if grp != "." else "(root)"
        out.append(f"<h2>{html.escape(label)}</h2><ul>")
        for rel in sorted(groups[grp]):
            href = html.escape("/".join(rel.parts))
            out.append(f'<li><a href="{href}">{html.escape(rel.stem)}</a></li>')
        out.append("</ul>")
    out.append("</body></html>")

    (root / "index.html").write_text("\n".join(out), encoding="utf-8")
    print(f"index.html written: {len(pages)} notebooks, {len(groups)} dirs")
    return 0


if __name__ == "__main__":
    sys.exit(main())
